# Generated by Django 5.2.8 on 2025-11-25 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='mid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock.medicinemaster'),
        ),
    ]
