# Generated by Django 5.2.8 on 2025-11-25 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_no', models.CharField(max_length=50)),
                ('bill_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.medicinemaster')),
                ('bill_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.billmaster')),
            ],
        ),
    ]
