# Generated by Django 5.2.8 on 2025-12-01 09:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_remove_billmaster_bill_no_alter_billdetails_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billmaster',
            name='bill_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
