# Generated by Django 5.2.8 on 2025-12-01 15:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_alter_billmaster_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billmaster',
            name='bill_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
