# Generated by Django 5.2.8 on 2025-12-01 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_alter_billmaster_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billmaster',
            name='bill_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 1, 15, 38, 16, 845924, tzinfo=datetime.timezone.utc)),
        ),
    ]
