# Generated by Django 5.2.8 on 2025-12-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0007_alter_billmaster_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billmaster',
            name='bill_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
